# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:27:38+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import UploadFile

from models import (
    V1AddPasswordPostResponse,
    V1AddRestrictionsPostResponse,
    V1AddWatermarkImagePostResponse,
    V1AddWatermarkTextPostResponse,
    V1ExtractPagesPostResponse,
    V1MergeDocumentsPostResponse,
    V1RemovePagesPostResponse,
    V1RemovePasswordPostResponse,
    V1RemoveRestrictionsPostResponse,
    V1RemoveSignaturesPostResponse,
    V1ReversePagesPostResponse,
    V1RotatePagesPostResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@pdfblocks.com',
        'name': 'PDF Blocks Support',
        'url': 'https://www.pdfblocks.com/support',
    },
    description='PDF Blocks is a secure, reliable, and fast API to work with PDF documents. Actions include: Merge PDF documents, add or remove passwords, add watermarks, remove, extract, reverse, and rotate pages, and more.',
    termsOfService='https://www.pdfblocks.com/terms',
    title='PDF Blocks API',
    version='1.5.0',
    servers=[
        {
            'description': 'Global endpoint (default).',
            'url': 'https://api.pdfblocks.com',
        },
        {
            'description': 'European-only endpoint.',
            'url': 'https://eu.api.pdfblocks.com',
        },
    ],
)


@app.post(
    '/v1/add_password',
    description=""" Protect a PDF document with a password. Encrypt the PDF document to prevent unauthorized access. """,
    tags=['pdf_security_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def add_password_v1(file: UploadFile):
    """
    Add a password to a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/add_restrictions',
    description=""" Add restrictions to prevent copying, printing, and modifying a PDF document. """,
    tags=['pdf_security_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def add_restrictions_v1(file: UploadFile):
    """
    Add restrictions to a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/add_watermark/image',
    description=""" Add an image watermark to each page of a PDF document. """,
    tags=['pdf_watermark_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def add_image_watermark_v1(file: UploadFile):
    """
    Add an image watermark to a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/add_watermark/text',
    description=""" Add a text watermark to each page of a PDF document. Choose from several watermark templates. """,
    tags=['pdf_watermark_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def add_text_watermark_v1(file: UploadFile):
    """
    Add a text watermark to a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/extract_pages',
    description=""" Extract one or more pages from a PDF document. """,
    tags=['pdf_page_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def extract_pages_v1(file: UploadFile):
    """
    Extract pages from a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/merge_documents',
    description=""" Combine multiple PDF documents into a single PDF document. """,
    tags=['pdf_document_organization'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def merge_documents_v1(file: UploadFile):
    """
    Merge PDF documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/remove_pages',
    description=""" Remove one or more pages from a PDF document. """,
    tags=['pdf_page_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def remove_pages_v1(file: UploadFile):
    """
    Remove pages from a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/remove_password',
    description=""" Remove the password from an encrypted PDF document. The PDF document will no longer require a password to open. """,
    tags=['pdf_security_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def remove_password_v1(file: UploadFile):
    """
    Remove the password from a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/remove_restrictions',
    description=""" Remove all the restrictions from a PDF document. """,
    tags=['pdf_security_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def remove_restrictions_v1(file: UploadFile):
    """
    Remove the restrictions from a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/remove_signatures',
    description=""" Remove the cryptographic signatures and timestamps from a PDF document. """,
    tags=['pdf_security_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def remove_signatures_v1(file: UploadFile):
    """
    Remove the signatures from a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/reverse_pages',
    description=""" Reverse the order of the pages of a PDF document. """,
    tags=['pdf_page_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def reverse_pages_v1(file: UploadFile):
    """
    Reverse the pages of a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/rotate_pages',
    description=""" Rotate one or more pages in a PDF document. """,
    tags=['pdf_page_operations'],
    security=[
        APIKeyHeader(name="X-Api-Key"),
    ],
)
def rotate_pages_v1(file: UploadFile):
    """
    Rotate pages in a PDF
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
