# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:27:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, confloat, conint, constr


class EncryptionAlgorithm(Enum):
    AES_128 = 'AES-128'
    AES_256 = 'AES-256'


class V1AddPasswordPostRequest(BaseModel):
    encryption_algorithm: Optional[EncryptionAlgorithm] = Field(
        'AES-128',
        description='The algorithm used to encrypt the PDF document.',
        examples=['AES-128'],
    )
    file: bytes = Field(..., description='The input PDF document')
    password: constr(pattern=r'^[\x20-\x7e]{4,32}$', min_length=4, max_length=32) = (
        Field(
            ...,
            description='The password required to open the file.',
            examples=['pa$$word'],
        )
    )


class V1AddPasswordPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1AddRestrictionsPostRequest(BaseModel):
    allow_accessibility: Optional[bool] = Field(
        True,
        description="If false, accessibility programs can't read the text or images of the document.",
    )
    allow_assemble_document: Optional[bool] = Field(
        True,
        description="If false, the user can't assemble or manipulate the document.",
    )
    allow_change_content: Optional[bool] = Field(
        True, description="If false, the user can't change the content of the document."
    )
    allow_comment_and_fill_form: Optional[bool] = Field(
        True,
        description="If false, the user can't add, edit or modify annotations or fill form fields.",
    )
    allow_copy_content: Optional[bool] = Field(
        True,
        description="If false, the user can't copy text and images to the clipboard.",
    )
    allow_fill_form: Optional[bool] = Field(
        True, description="If false, the user can't fill forms fields."
    )
    allow_print: Optional[bool] = Field(
        True, description="If false, the user can't print the document."
    )
    allow_print_high_resolution: Optional[bool] = Field(
        True,
        description="If false, the user can't print the document in high resolution.",
    )
    encryption_algorithm: Optional[EncryptionAlgorithm] = Field(
        'AES-128',
        description='The algorithm used to encrypt the PDF document.',
        examples=['AES-128'],
    )
    file: bytes = Field(..., description='The input PDF document')
    owner_password: constr(
        pattern=r'^[\x20-\x7e]{4,32}$', min_length=4, max_length=32
    ) = Field(
        ...,
        description='The password required to open and change permissions of the PDF document.',
        examples=['pa$$word'],
    )
    user_password: Optional[
        constr(pattern=r'^[\x20-\x7e]{4,32}$', min_length=4, max_length=32)
    ] = Field(
        None,
        description='The password required to open the PDF document. If the `user_password` is not set, the user will be able to open the document without a password.',
        examples=['pa$$word'],
    )


class V1AddRestrictionsPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1AddWatermarkImagePostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')
    image: bytes = Field(
        ...,
        description='The image to add as a watermark. The format of the image can be either PNG or JPEG.',
    )
    margin: Optional[confloat(ge=0.0)] = Field(
        1,
        description='The distance in inches from the border of the page to the image watermark.',
        examples=[1],
    )
    transparency: Optional[conint(ge=0, le=100)] = Field(
        50,
        description='The transparency level for the image watermark from 0 (opaque) to 100 (transparent).',
        examples=[50],
    )


class V1AddWatermarkImagePostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class Color(Enum):
    Red = 'Red'
    Blue = 'Blue'
    Gray = 'Gray'
    Black = 'Black'


class V1AddWatermarkTextPostRequest(BaseModel):
    color: Optional[Color] = Field(
        'Gray', description='The color of the text watermark.', examples=['Gray']
    )
    file: bytes = Field(..., description='The input PDF document')
    line_1: constr(max_length=32) = Field(
        ...,
        description='The first line of text of the watermark.',
        examples=['Jane Doe'],
    )
    line_2: Optional[constr(max_length=32)] = Field(
        None,
        description='The second line of text of the watermark.',
        examples=['ACME, Inc'],
    )
    line_3: Optional[constr(max_length=32)] = Field(
        None,
        description='The third line of text of the watermark.',
        examples=['Confidential'],
    )
    margin: Optional[confloat(ge=0.0)] = Field(
        1,
        description='The distance in inches from the border of the page to the text watermark.',
        examples=[1],
    )
    template: Optional[conint(ge=1001, le=66537)] = Field(
        1001,
        description='The [id of the text watermark template](https://www.pdfblocks.com/docs/api/v1/text-watermark-templates.pdf).',
        examples=[1001],
    )
    transparency: Optional[conint(ge=0, le=100)] = Field(
        75,
        description='The transparency level for the text watermark from 0 (opaque) to 100 (transparent).',
        examples=[75],
    )


class V1AddWatermarkTextPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1ExtractPagesPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')
    first_page: Optional[conint(ge=1)] = Field(
        None,
        description='The first page of the range to extract. If empty, it defaults to the first page of the PDF document.',
    )
    last_page: Optional[conint(ge=1)] = Field(
        None,
        description='The last page of the range to extract. If empty, it defaults to the last page of the PDF document.',
    )


class V1ExtractPagesPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1MergeDocumentsPostRequest(BaseModel):
    file: Optional[List[bytes]] = Field(
        None,
        description='The array of PDF documents. PDF documents will be merged in the same order they are inserted into this array.',
    )


class V1MergeDocumentsPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1RemovePagesPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')
    first_page: Optional[conint(ge=1)] = Field(
        None,
        description='The first page of the range to remove from the PDF document. If empty, it defaults to the first page of the document.',
    )
    last_page: Optional[conint(ge=1)] = Field(
        None,
        description='The last page of the range to remove from the PDF document. If empty, it defaults to the last page of the document.',
    )


class V1RemovePagesPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1RemovePasswordPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')
    password: constr(max_length=256) = Field(
        ...,
        description='The password required to open the file.',
        examples=['pa$$word'],
    )


class V1RemovePasswordPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1RemoveRestrictionsPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')


class V1RemoveRestrictionsPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1RemoveSignaturesPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')


class V1RemoveSignaturesPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class V1ReversePagesPostRequest(BaseModel):
    file: bytes = Field(..., description='The input PDF document')


class V1ReversePagesPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class Angle(Enum):
    integer_0 = 0
    integer_90 = 90
    integer_180 = 180
    integer_270 = 270
    integer__90 = -90
    integer__180 = -180
    integer__270 = -270


class V1RotatePagesPostRequest(BaseModel):
    angle: Angle = Field(
        ...,
        description='The angle of rotation of the pages. Positive angles rotate the pages clockwise. Negative angles rotate the pages counter-clockwise.',
        examples=[90],
    )
    file: bytes = Field(..., description='The input PDF document')
    first_page: Optional[conint(ge=1)] = Field(
        None,
        description='The first page of the range to rotate in the PDF document. If empty, it defaults to the first page of the document.',
    )
    last_page: Optional[conint(ge=1)] = Field(
        None,
        description='The last page of the range to rotate in the PDF document. If empty, it defaults to the last page of the document.',
    )


class V1RotatePagesPostResponse(BaseModel):
    errors: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None
